// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj4v7S59dU9tFDgwpYzytBbjFqJEWoe6k',
    appId: '1:865864145623:web:4359b4a68bed510ed52e92',
    messagingSenderId: '865864145623',
    projectId: 'nobox-chat-akbar',
    authDomain: 'nobox-chat-akbar.firebaseapp.com',
    storageBucket: 'nobox-chat-akbar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW5Pe6vhQcAyYOy3eifwYA_GfBFdMFG-k',
    appId: '1:865864145623:android:b9013fe9de650b66d52e92',
    messagingSenderId: '865864145623',
    projectId: 'nobox-chat-akbar',
    storageBucket: 'nobox-chat-akbar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALO0pIVmUPBBYd1ZrQs9uUZ_zbpewiHTA',
    appId: '1:865864145623:ios:aef6742f3356fac1d52e92',
    messagingSenderId: '865864145623',
    projectId: 'nobox-chat-akbar',
    storageBucket: 'nobox-chat-akbar.firebasestorage.app',
    iosBundleId: 'com.example.noboxChatBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALO0pIVmUPBBYd1ZrQs9uUZ_zbpewiHTA',
    appId: '1:865864145623:ios:aef6742f3356fac1d52e92',
    messagingSenderId: '865864145623',
    projectId: 'nobox-chat-akbar',
    storageBucket: 'nobox-chat-akbar.firebasestorage.app',
    iosBundleId: 'com.example.noboxChatBasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj4v7S59dU9tFDgwpYzytBbjFqJEWoe6k',
    appId: '1:865864145623:web:f798b45619020c95d52e92',
    messagingSenderId: '865864145623',
    projectId: 'nobox-chat-akbar',
    authDomain: 'nobox-chat-akbar.firebaseapp.com',
    storageBucket: 'nobox-chat-akbar.firebasestorage.app',
  );
}
